### ISSUE TITLE
How to install when HA is installed in Python virtualenv

### ISSUE THREAD

**Issue by parautenbach** [basnijholt/lovelace-ios-themes#10]
I know this is technically a HA question, but I couldn't find an answer in the docs or the community forum. Would you mind to include some pointers on how to install this when one has e.g. installed HA on a Raspberry PI in a Python virtualenv? Does one simply create a `themes` directory and copy some files? Scanning this repo briefly, it looks like I only need `settings-light-dark.yaml`, run `create-themes.py` and copy the files to the `themes` directory.

**Comment by basnijholt** [comment]
You can still install HACS in that case, which is what I would recommend doing.
Then use HACS to install the themes.

**Comment by parautenbach** [comment]
Thanks, I'll do that.
