### ISSUE TITLE
After latest update I'm not seeing a color change to indicate if a button is on or off.

### ISSUE THREAD

**Issue by natemcg** [basnijholt/lovelace-ios-themes#11]
It used to change the icon to yellow if something was on, now it doesn't change color to show the status.

**Comment by basnijholt** [comment]
The meaning of the `-alternative` suffix has changed.

See the [release notes](https://github.com/basnijholt/lovelace-ios-themes/releases).

**Comment by RezzZ** [comment]
@basnijholt so no way to display state colours any more with this cool skin?

**Comment by basnijholt** [comment]
Yes, just choosing `ios-light-mode-dark-green` instead of `ios-light-mode-dark-green-alternative`.

**Comment by RezzZ** [comment]
ok, works again now. thanks!
