### ISSUE TITLE
All dark themes have an orange header

### ISSUE THREAD

**Issue by ljmerza** [basnijholt/lovelace-ios-themes#3]
No matter what dark theme I change the theme to all the headers are orange. In the map, overview, settings, etc. This is the ios-dark-mode-light-blue:
![image](https://user-images.githubusercontent.com/4085765/74490469-9a5bf480-4e96-11ea-8be7-56a1be9cf407.png)

Im using home assistant 0.105.3

all the links and icons are orange too for all themes
![image](https://user-images.githubusercontent.com/4085765/74490589-00487c00-4e97-11ea-9a48-c536e866fe24.png)

**Comment by basnijholt** [comment]
That's by design. Did you install the custom header?

**Comment by ljmerza** [comment]
bright orange? admittedly i dont use apple but damn thats ugly

**Comment by basnijholt** [comment]
You are welcome to submit a PR if you think you can make it prettier.
