### ISSUE TITLE
Problem after upgrade to 2022.3.X with black letters on black backround

### ISSUE THREAD

**Issue by 03397** [basnijholt/lovelace-ios-themes#35]
After the upgrade to new version black background with black letters make reading very difficult. There are more than the ones attached.

**Comment by 03397** [comment]
Attaching screenshots 
![Uploading Screenshot_20220307-223922.png…]()

**Comment by 03397** [comment]
![Screenshot_20220307-223940](https://user-images.githubusercontent.com/6150853/157185386-870c7af0-c28c-4839-80d4-d41850fc56b0.png)

**Comment by 03397** [comment]
Attaching screenshots 
![Uploading Screenshot_20220307-223922.png…]()

**Comment by 03397** [comment]
![Screenshot_20220307-223940](https://user-images.githubusercontent.com/6150853/157185548-cfc80774-1878-4abb-901b-e738c8016650.png)

**Comment by 03397** [comment]
![Screenshot_20220307-223922](https://user-images.githubusercontent.com/6150853/157186175-db841138-20a1-4b81-87ba-3c4d1bc6d570.png)

**Comment by Herbs851** [comment]
Hi same problem here, i just modify like this : 

```
  mdc-text-field-fill-color: none
  mdc-text-field-ink-color: var(--primary-text-color)
  mdc-select-ink-color: var(--primary-text-color)
  mdc-select-fill-color: none
  mdc-select-label-ink-color: var(--primary-text-color)
```
Now i try to get underline and icone white...

![image](https://user-images.githubusercontent.com/51154851/157214164-b369149d-a4c1-4aa0-b9f5-0804191cb798.png)

**Comment by basnijholt** [comment]
Please report in #34.

I have responded there.
