### ISSUE TITLE
alternate theme?

### ISSUE THREAD

**Issue by lollo78** [basnijholt/lovelace-ios-themes#4]
Hi, I installed the lovelace ios Themes from HACS and I followed your guide on Github to add also the automation (basnijholt/home-assistant-config/automations/frontend.yaml), but I can't see differences beetwen "regular" and "-alternate" themes. Nothing seems to change.

**Comment by basnijholt** [comment]
Basically it has switches color yellow depending on the state.

The difference used to be bigger, but now HA by default doesn't color everything when some state is on, so the differences aren't obvious.

**Comment by basnijholt** [comment]
I've been thinking about removing the alternative theme, but I don't work to break people's configs.

**Comment by lollo78** [comment]
maybe you could leave it and use -alternate to perform more graphical changes. For example you could change the orange color inside text, bar...

**Comment by caseyjhol** [comment]
I guess if you were going to remove one, it seems like it would make more sense to rename -alt to make it the main one. Without the yellow color, you can't tell if a switch is on or off.

**Comment by basnijholt** [comment]
I think the same, but I have been hesitant in doing so because I don't want to break people's themes.

**Comment by caseyjhol** [comment]
Best method would be to probably start doing official releases with version numbers, then if you decide to implement breaking changes it'll be easier for people to control.

**Comment by basnijholt** [comment]
good idea! I’ll do that.

**Comment by basnijholt** [comment]
@caseyjhol, @lollo78, I have created an official release now. 
* v1.0.0 has the old behavior
* v2.0.0 has the default theme with colored active state switches

**Comment by caseyjhol** [comment]
It seems like you might've switched the names *and* switched the active colors, making the theme the same as before.

![image](https://user-images.githubusercontent.com/2874325/85208412-93823a00-b2ed-11ea-9fdb-543d29413f10.png)

**Comment by basnijholt** [comment]
Oops 😅

https://github.com/basnijholt/lovelace-ios-themes/releases/tag/v2.1.0
