### ISSUE TITLE
Compatibility with Home Assistant 2022.11.0

### ISSUE THREAD

**Issue by JurajNyiri** [basnijholt/lovelace-ios-themes#40]
Home Assistant 2022.11.0 adds borders around every card which looks terrible, especially with a nice theme like this.

![image](https://user-images.githubusercontent.com/5785999/199708757-103e016c-ee32-46ec-9e1d-be417ae4c06a.png)

Could we remove them? Thank you!

**Comment by InfinityATX** [comment]
Also seeing this, and hate it. Will watch for an update!

**Comment by basnijholt** [comment]
This is fixed now :)
