### ISSUE TITLE
Background not working 

### ISSUE THREAD

**Issue by ca1p3** [basnijholt/lovelace-ios-themes#47]
hi all first I just want to thank you for these amazing theme.
I now have a problem that my background Is grey on all the different themes, how do I fix this ?

**Comment by t0kn4r** [comment]
got the same problem. this helped so far:
[adding a background in RAW confing](https://community.home-assistant.io/t/how-to-add-a-picture-as-a-lovelace-background/169050/4)
not so elegant but works ;)
[blue/red img](https://raw.githubusercontent.com/basnijholt/lovelace-ios-dark-mode-theme/master/backgrounds/homekit-bg-4.jpeg)

**Comment by SwannyBFC** [comment]
Same issue here nuc with latest HA. I just have a black back ground, should be dark mode red-blue

**Comment by ca1p3** [comment]
> Same issue here nuc with latest HA. I just have a black back ground, should be dark mode red-blue

Same here love the dark red blue, it seems like the pathway to the image is the problem

**Comment by t0kn4r** [comment]
> Same issue here nuc with latest HA. I just have a black back ground, should be dark mode red-blue



> > Same issue here nuc with latest HA. I just have a black back ground, should be dark mode red-blue
> 
> Same here love the dark red blue, it seems like the pathway to the image is the problem

you can solve it with my unelegant way until its solved :)

**Comment by basnijholt** [comment]
I am on vacation at the moment, so if anybody can submit a pull request, I’m happy to except it.

**Comment by kirush0280** [comment]
+ for problem
Home Assistant 2022.12.8
Supervisor 2022.12.1
Frontend 20221213.1 - latest
In console:
GET http://192.168.100.129:8123/hacsfiles/themes/ios-themes/homekit-bg-blue-red.jpg 404 (Not Found)
![2022-12-29_00-44](https://user-images.githubusercontent.com/13412942/209875665-b1719839-c33b-43d2-9484-d9af6209673b.png)

**Comment by nalin29** [comment]
This can be solved by copying over the image files to the correct location in /config/www/custom_components/themes/ios-themes/ . Not sure why they got deleted after update reinstalling via HACS did not solve this so I manually copied the background files to the expected locations.

**Comment by nalin29** [comment]
Looking at a diff from last HACS release it looks like changes were made for populating the public endpoints under /hacsfiles to be asynchronous in this [commit](https://github.com/hacs/integration/compare/1.28.4...1.29.0#diff-49e399d00036b3a319719192cd99a76fd838f6c9f2c01e026b666e605a65de27) perhaps this is not working as intended and preventing the files from being copied over.

**Comment by kirush0280** [comment]
> This can be solved by copying over the image files to the correct location in /config/www/community/themes/ios-themes/ . Not sure why they got deleted after update. Reinstalling via HACS did not remedy this. So I manually copied the background files to the expected locations. This may also have been related to the recent HACS update but I cannot confirm since I updated both Home Assistant and HACS at the same time without reloading.

+1 Yes, its helps.

**Comment by Daw34** [comment]
Cześć, jakie pliki mam skopiować ?

**Comment by Daw34** [comment]
> > This can be solved by copying over the image files to the correct location in /config/www/community/themes/ios-themes/ . Not sure why they got deleted after update. Reinstalling via HACS did not remedy this. So I manually copied the background files to the expected locations. This may also have been related to the recent HACS update but I cannot confirm since I updated both Home Assistant and HACS at the same time without reloading.
> 
> +1 Yes, its helps.

Hi, what files should I upload?

**Comment by sddgit** [comment]
I too have run into this problem after installing the latest HACS and HA at the same time. I’ve tried copying the images around to various locations, but haven't got anywhere yet. Any more detailed pointers would be appreciated.

**Comment by sddgit** [comment]
Does anyone have any clue yet why this has happened exactly? My themes are all in /config/themes. Within that folder there is, of course, ios-themes, that contains the theme and all the background images. The themes themselves point to /hacsfiles/themes/ios-themes to get the background images. This, in effect, is /config/www/community/themes/ios-themes. Sure enough, creating that folder and copying all the jpg's there fixes the issue (as suggested above). But does that mean that path existed previously, perhaps created during the theme installation, but has now somehow been deleted?

**Comment by mjakeseaton** [comment]
> This can be solved by copying over the image files to the correct location in /config/www/community/themes/ios-themes/ . Not sure why they got deleted after update. Reinstalling via HACS did not remedy this. So I manually copied the background files to the expected locations. This may also have been related to the recent HACS update but I cannot confirm since I updated both Home Assistant and HACS at the same time without reloading.

This did the trick.

**Comment by erugaman** [comment]
> > > This can be solved by copying over the image files to the correct location in /config/www/community/themes/ios-themes/ . Not sure why they got deleted after update. Reinstalling via HACS did not remedy this. So I manually copied the background files to the expected locations. This may also have been related to the recent HACS update but I cannot confirm since I updated both Home Assistant and HACS at the same time without reloading.
> > 

 +2 Yes, its helps.

**Comment by AFPhome** [comment]
> > > > This can be solved by copying over the image files to the correct location in /config/www/community/themes/ios-themes/ . Not sure why they got deleted after update. Reinstalling via HACS did not remedy this. So I manually copied the background files to the expected locations. This may also have been related to the recent HACS update but I cannot confirm since I updated both Home Assistant and HACS at the same time without reloading.
> 
> +2 Yes, its helps.

Will you be so kind to be more specific please. Where did you exacly copied the image files, witch directory? and witch files?
Try everything but so far no luck.
thx in advanced

**Comment by sddgit** [comment]
> Will you be so kind to be more specific please. Where did you exacly copied the image files, witch directory? and witch files? Try everything but so far no luck. thx in advanced

You need to copy the jpg files to /config/www/community/themes/ios-themes. Create any folders that don’t already exist. You will have to refresh your browser/app to see any changes I think.

**Comment by erugaman** [comment]
> > Will you be so kind to be more specific please. Where did you exacly copied the image files, witch directory? and witch files? Try everything but so far no luck. thx in advanced
> 
> You need to copy the jpg files to /config/www/community/themes/ios-themes. Create any folders that don’t already exist. You will have to refresh your browser/app to see any changes I think.

The original files are located in:   /config/themes/ios-themes/*.*

Move them or copy them to:   /config/www/community/themes/ios-themes/*.*

1.- first create the directory structure 
2.- be sure to make this change inside the configure.yaml

         frontend: 
           #themes: !include /config/themes/ios-themes/ios-themes.yaml
           themes: !include_dir_merge_named themes

That's all.

**Comment by basnijholt** [comment]
I don't understand why you guys are having issues?

I just uninstalled the themes and reinstalled them, and everything worked just fine.

**Comment by mjakeseaton** [comment]
> I don't understand why you guys are having issues?
> 
> I just uninstalled the themes and reinstalled them, and everything worked just fine.

Maybe the latest Home Assistant update fixed it?

**Comment by bcmitri** [comment]
> I don't understand why you guys are having issues?
> 
> I just uninstalled the themes and reinstalled them, and everything worked just fine.

Mine worked fine for a while on some devices, but not on others. When it failed varied from one device to the next, so I assume it was the result of caching. 

Implementing the fix above fixed it for all my devices (and other themes that were impacted by the same issue).

**Comment by AFPhome** [comment]
> > > Will you be so kind to be more specific please. Where did you exacly copied the image files, witch directory? and witch files? Try everything but so far no luck. thx in advanced
> > 
> > 
> > You need to copy the jpg files to /config/www/community/themes/ios-themes. Create any folders that don’t already exist. You will have to refresh your browser/app to see any changes I think.
> 
> The original files are located in: /config/themes/ios-themes/_._
> 
> Move them or copy them to: /config/www/community/themes/ios-themes/_._
> 
> 1.- first create the directory structure 2.- be sure to make this change inside the configuration.yaml
> 
> ```
>      frontend: 
>        #themes: !include /config/themes/ios-themes/ios-themes.yaml
>        themes: !include_dir_merge_named themes
> ```
> 
> That's all.

Thx

Every theme works, -> EXCEPT !!!

ios-dark-mode-blue-red (I love that one)
ios-dark-mode-blue-red-alternative

Copy all the files, what can be wrong?

**Comment by ghzgod** [comment]
I agree, uninstall and reinstall did not fix this.  I think something persistent hangs even after uninstall.  But as mentioned by asemev, copying the files to the www folder fixed it immediately.

**Comment by brucek1642** [comment]
I think I found the the fix

Broken config
frontend:
  themes: !include_dir_merge_named themes/

Remove the / at the end of the line and now everything works. Something must have change in the last version or two

frontend:
  themes: !include_dir_merge_named themes

**Comment by sddgit** [comment]
Mine has never had the trailing slash…

**Comment by Ringo982** [comment]
the workaround did not worked for me.
My configuration.yaml contains:
frontend:
# your configuration.
   themes: !include_dir_merge_named themes
# your configuration.


and i moved files to /config/www/community/themes/ios-themes

but nothing changed also after a full restart of HA, and a full browser refresh

Need help...

**Comment by MikeMitterer** [comment]
OK, I'm running home assist in Docker. So - no HACS.
What I did:

Make sure you have this setting in configuration.yaml
```yaml
frontend:
  themes: !include_dir_merge_named themes
```

```bash
    # cd to the folder where your configuration.yaml is
    mkdir -p www/themes/ios-themes/
 
    # Clones this repo to tmp
    git clone https://github.com/basnijholt/lovelace-ios-themes.git tmp

   # Copy all images to the puplic ios-themes folder
   cp tmp/themes/*.jpg www/themes/ios-themes

   # Replace the hacsfiles-path with local-path and create the themes file
   cat tmp/themes/ios-themes.yaml | sed 's#/hacsfiles#/local#g' > themes/ios-themes.yaml

   # Remove the cloned tmp-Folder
   rm -rf tmp
```
Restart HA!

Hope this helps

**Comment by dMopp** [comment]
Why is the path wrong? Does this theme requires an update ?

**Comment by eilandert** [comment]
> OK, I'm running home assist in Docker. So - no HACS. What I did:
> 
> Make sure you have this setting in configuration.yaml
> 
> ```yaml
> frontend:
>   themes: !include_dir_merge_named themes
> ```
> 
> ```shell
>     # cd to the folder where your configuration.yaml is
>     mkdir -p www/themes/ios-themes/
>  
>     # Clones this repo to tmp
>     git clone https://github.com/basnijholt/lovelace-ios-themes.git tmp
> 
>    # Copy all images to the puplic ios-themes folder
>    cp tmp/themes/*.jpg www/themes/ios-themes
> 
>    # Replace the hacsfiles-path with local-path and create the themes file
>    cat tmp/themes/ios-themes.yaml | sed 's#/hacsfiles#/local#g' > themes/ios-themes.yaml
> 
>    # Remove the cloned tmp-Folder
>    rm -rf tmp
> ```
> 
> Restart HA!
> 
> Hope this helps

This helps, thank you

**Comment by jarodwsams** [comment]
> You need to copy the jpg files to /config/www/community/themes/ios-themes. Create any folders that don’t already exist. You will have to refresh your browser/app to see any changes I think.
> 
> The original files are located in: /config/themes/ios-themes/_._
> 
> Move them or copy them to: /config/www/community/themes/ios-themes/_._
> 
> 1.- first create the directory structure 2.- be sure to make this change inside the configuration.yaml
> 
> ```
>      frontend: 
>        #themes: !include /config/themes/ios-themes/ios-themes.yaml
>        themes: !include_dir_merge_named themes
> ```

To add a little specificity, because this just worked for me:
Whether you're running HA as the OS or in a Docker, simply run these two commands from the root of your configuration directory (probably `/config`):
```
mkdir -p www/community/themes/ios-themes
cp themes/ios-themes/*.jpg www/community/themes/ios-themes
```
Restart HA using the method appropriate for your deployment, and viola!
(I did not have to modify my `configuration.yaml` file. It already had the `themes: !include_dir_merge_named themes` line)

**Comment by CC-JION** [comment]
> > > Will you be so kind to be more specific please. Where did you exacly copied the image files, witch directory? and witch files? Try everything but so far no luck. thx in advanced
> > 
> > 
> > You need to copy the jpg files to /config/www/community/themes/ios-themes. Create any folders that don’t already exist. You will have to refresh your browser/app to see any changes I think.
> 
> The original files are located in: /config/themes/ios-themes/_._
> 
> Move them or copy them to: /config/www/community/themes/ios-themes/_._
> 
> 1.- first create the directory structure 2.- be sure to make this change inside the configuration.yaml
> 
> ```
>      frontend: 
>        #themes: !include /config/themes/ios-themes/ios-themes.yaml
>        themes: !include_dir_merge_named themes
> ```
> 
> That's all.

work for me😐

**Comment by Maximilian118** [comment]
For me, I didn't need to change much at all. It's just about making sure the ios-themes.yaml is pointing at the jpeg files. My process was this:

1. Make sure you have this entry in your configuration.yaml document:
```
frontend:
  themes: !include_dir_merge_named themes
```
2. As described by [erugaman](https://github.com/erugaman) above, create this directory structure: /config/www/community/themes/ios-themes/. It doesn't actually have to be this. Anywhere in the www folder will do.
3. Copy only the jpeg files over to the new ios-themes folder but leave the ios-themes.yaml document where it is.
4. Open ios-themes.yaml and change all of the URL's to reflect the new location of your jpeg files. For example I changed mine to:
```
background-image: "center / cover no-repeat fixed url('/local/community/themes/ios-themes/homekit-bg-dark-green.jpeg')"
```

Note: "local" is referencing the www folder.

**Comment by ScottEKendall** [comment]
> For me, I didn't need to change much at all. It's just about making sure the ios-themes.yaml is pointing at the jpeg files. My process was this:
> 
> 1. Make sure you have this entry in your configuration.yaml document:
> 
> ```
> frontend:
>   themes: !include_dir_merge_named themes
> ```
> 
>  2. As described by [erugaman](https://github.com/erugaman) above, create this directory structure: /config/www/community/themes/ios-themes/. It doesn't actually have to be this. Anywhere in the www folder will do.
> 3. Copy only the jpeg files over to the new ios-themes folder but leave the ios-themes.yaml document where it is.
> 4. Open ios-themes.yaml and change all of the URL's to reflect the new location of your jpeg files. For example I changed mine to:
> 
> ```
> background-image: "center / cover no-repeat fixed url('/local/community/themes/ios-themes/homekit-bg-dark-green.jpeg')"
> ```
> 
> Note: "local" is referencing the www folder.

This worked PERFECTLY!  glad this was the fix...it was driving me nuts why all of my backgrounds disappeared...

**Comment by Neonodes** [comment]
> > For me, I didn't need to change much at all. It's just about making sure the ios-themes.yaml is pointing at the jpeg files. My process was this:
> > 
> > 1. Make sure you have this entry in your configuration.yaml document:
> > 
> > ```
> > frontend:
> >   themes: !include_dir_merge_named themes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. As described by [erugaman](https://github.com/erugaman) above, create this directory structure: /config/www/community/themes/ios-themes/. It doesn't actually have to be this. Anywhere in the www folder will do.
> > 3. Copy only the jpeg files over to the new ios-themes folder but leave the ios-themes.yaml document where it is.
> > 4. Open ios-themes.yaml and change all of the URL's to reflect the new location of your jpeg files. For example I changed mine to:
> > 
> > ```
> > background-image: "center / cover no-repeat fixed url('/local/community/themes/ios-themes/homekit-bg-dark-green.jpeg')"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Note: "local" is referencing the www folder.
> 
> This worked PERFECTLY! glad this was the fix...it was driving me nuts why all of my backgrounds disappeared...



> For me, I didn't need to change much at all. It's just about making sure the ios-themes.yaml is pointing at the jpeg files. My process was this:
> 
> 1. Make sure you have this entry in your configuration.yaml document:
> 
> ```
> frontend:
>   themes: !include_dir_merge_named themes
> ```
> 
> 2. As described by [erugaman](https://github.com/erugaman) above, create this directory structure: /config/www/community/themes/ios-themes/. It doesn't actually have to be this. Anywhere in the www folder will do.
> 3. Copy only the jpeg files over to the new ios-themes folder but leave the ios-themes.yaml document where it is.
> 4. Open ios-themes.yaml and change all of the URL's to reflect the new location of your jpeg files. For example I changed mine to:
> 
> ```
> background-image: "center / cover no-repeat fixed url('/local/community/themes/ios-themes/homekit-bg-dark-green.jpeg')"
> ```
> 
> Note: "local" is referencing the www folder.

Hands down the best solutions out there and it works!
Thanks!

**Comment by Neonodes** [comment]
> > For me, I didn't need to change much at all. It's just about making sure the ios-themes.yaml is pointing at the jpeg files. My process was this:
> > 
> > 1. Make sure you have this entry in your configuration.yaml document:
> > 
> > ```
> > frontend:
> >   themes: !include_dir_merge_named themes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. As described by [erugaman](https://github.com/erugaman) above, create this directory structure: /config/www/community/themes/ios-themes/. It doesn't actually have to be this. Anywhere in the www folder will do.
> > 3. Copy only the jpeg files over to the new ios-themes folder but leave the ios-themes.yaml document where it is.
> > 4. Open ios-themes.yaml and change all of the URL's to reflect the new location of your jpeg files. For example I changed mine to:
> > 
> > ```
> > background-image: "center / cover no-repeat fixed url('/local/community/themes/ios-themes/homekit-bg-dark-green.jpeg')"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Note: "local" is referencing the www folder.
> 
> This worked PERFECTLY! glad this was the fix...it was driving me nuts why all of my backgrounds disappeared...

Sames here, works like a charm! Thanks a lot for the solution!

**Comment by khalilbeby** [comment]
> I don't understand why you guys are having issues?
> 
> I just uninstalled the themes and reinstalled them, and everything worked just fine.

when i chenge themes background not changed

**Comment by markcichy** [comment]
> > > For me, I didn't need to change much at all. It's just about making sure the ios-themes.yaml is pointing at the jpeg files. My process was this:
> > > 
> > > 1. Make sure you have this entry in your configuration.yaml document:
> > > 
> > > ```
> > > frontend:
> > >   themes: !include_dir_merge_named themes
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 2. As described by [erugaman](https://github.com/erugaman) above, create this directory structure: /config/www/community/themes/ios-themes/. It doesn't actually have to be this. Anywhere in the www folder will do.
> > > 3. Copy only the jpeg files over to the new ios-themes folder but leave the ios-themes.yaml document where it is.
> > > 4. Open ios-themes.yaml and change all of the URL's to reflect the new location of your jpeg files. For example I changed mine to:
> > > 
> > > ```
> > > background-image: "center / cover no-repeat fixed url('/local/community/themes/ios-themes/homekit-bg-dark-green.jpeg')"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Note: "local" is referencing the www folder.
> > 
> > 
> > This worked PERFECTLY! glad this was the fix...it was driving me nuts why all of my backgrounds disappeared...
> 
> Same here, works like a charm! Thanks a lot for the solution!

So, this kinda worked. It solved the repointing. However, doesn't matter which theme variant I choose, I always get the '''homekit-bg-blue-red.jpg''' as the background JPEG. Even though they are all in the new dir and properly ref'd in the *.yaml config.

Any ideas?

**Comment by broyuken** [comment]
I made all the changes to the yaml and moved the images but it still doesn’t work.

**Comment by eilandert** [comment]
I have a Homeassistant Yellow, I have to do the following to make it work:  (after updates too, I guess)

sed -i s/hacsfiles/local/g /homeassistant/themes/ios-themes/ios-themes.yaml

**Comment by FoX2V** [comment]
> Note: "local" is referencing the www folder.

i love you man... thx!

**Comment by basnijholt** [comment]
Hey everyone,

Thanks for all the feedback! The background issue you're describing was related to an older version of the theme, before we switched to base64 or remote URLs for the images. This caused issues with image paths (e.g., `/hacsfiles`) not loading correctly.

### The Good News:
As of **v3.0.0**, this issue should be **completely resolved**.  
- Themes now use **remote background URLs** by default for quicker loading and caching.
- Want to use **local files** instead? You can, with the `-alternative` themes. You just need to put the images in `/config/www/ios-themes` and everything should work seamlessly now!

### What's Next:
- Simply **update to v3.0.0** via **HACS** and everything should work without any manual fixing.
- I've also updated the **[README](https://github.com/basnijholt/lovelace-ios-themes)** with **clearer instructions** for local background use, including quick commands to download the images for those using the `-alternative` themes.

Thanks again for your patience and help! If you still have issues or questions, let me know.

– Bas (@basnijholt)
