### ISSUE TITLE
stuck on install

### ISSUE THREAD

**Issue by rchadgray** [basnijholt/lovelace-ios-themes#51]
So i have HACs installed and this ios-themes under Frontends in HACs.

I am on the step to edit the lovelace-ui.yaml.

I cannot find the "RAW" editor.  Or the location of this file...  

I have "file editor" installed, but i also cannot find the lovelace-ui.yaml file.

I am kind of lost if i can get some help.

**Comment by rchadgray** [comment]
Ah... found them under my User Name > Themes...  

Sorry i am such a newbie.

**Comment by mrfy** [comment]
@rchadgray you managed to find "lovelace-ui.yaml" file under "under my User Name > Themes..." ? Thanks, I cant find... :)
