### ISSUE TITLE
Theme is broken since update 2023.04.0

### ISSUE THREAD

**Issue by cosmos1978** [basnijholt/lovelace-ios-themes#54]
Theme wont load anymore since the latest update.

**Comment by Ringo982** [comment]
Same here.... the workaround to move files to /config/www/community/themes/ios-themes is not workng now...

**Comment by cazxtc** [comment]
same here :)

**Comment by Ste-Mzk** [comment]
Same here :(

**Comment by miktin** [comment]
Same here.

**Comment by basnijholt** [comment]
Does anyone know what changed upstream in `core`?

**Comment by basnijholt** [comment]
https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer/ might be related

**Comment by David6951** [comment]
Same

**Comment by Danit2** [comment]
It is working again with the update 2023.04.1

For me is all ok now.

**Comment by borez** [comment]
Agree - it is working again with 2023.04.1.

**Comment by basnijholt** [comment]
Great to hear! Thanks so much for reporting back 😄

**Comment by basnijholt** [comment]
Since multiple people have reported this as fixed, I will close this issue now. 

Please let me know whether this issue still occurs and then I will open again.

**Comment by nalin29** [comment]
Fixed in 2023.4.1 my themes are now working again.
