### ISSUE TITLE
How to change drop-down background menu color?

### ISSUE THREAD

**Issue by mkanet** [basnijholt/lovelace-ios-themes#58]
I know years ago, Home Assistant had a limitation where it inadvertently shared **_card-background-color_**  with unrelated theme colors such as dropdown menu background color.  I finally gave up trying to use transparent card backgrounds.

Have you figured out a way to define the color for the drop-down menu background color (without transparency) or at least add blur to the drop-down?

![image](https://github.com/basnijholt/lovelace-ios-themes/assets/811008/dd2d1884-33b9-4941-9ab9-4f286934a03a)

**Comment by Nezz** [comment]
The colors get linked here:
https://github.com/home-assistant/frontend/blob/dd082c204b45df55663dc257ee83f5efe1a9ab88/src/resources/styles-data.ts#L153

I don't really know how to get the blurring done nicely. The trouble is that the dropdown is a vaadin component and the `backdrop-filter` property is not exposed. The overlay itself is styled here:
https://github.com/vaadin/web-components/blob/a79c45f0a81c9a5da4ee1696873e5241e415710f/packages/vaadin-material-styles/mixins/overlay.js#L20
