### ISSUE TITLE
Can we make the backgrounds stick and not scroll please?

### ISSUE THREAD

**Issue by houser42** [basnijholt/lovelace-ios-themes#59]
Like these themes a lot. Many thanks!
Would just like to make the backgrounds in these themes stick and not scroll when swiping. 
Is that possible in a general setting for all themes in this git please?
I have tried using `card-mod` to no effect but something like the code below should work in theory.
But does not..
If it can be tweaked for these thees it would bre great, and if so where in the  `ios-themes.yaml` does it go?

```
card-mod-view: |
    :host {
      background: center / cover no-repeat url("/local/img/background.jpg") fixed !important;
    }
```

**Comment by Nezz** [comment]
This happens due to the iOS version of Safari not supporting `fixed` background attachment:
https://caniuse.com/background-attachment

On all other platforms it works correctly.

**Comment by Nezz** [comment]
The iOS HA app displays things as a web view. This issue therefore affects both Safari on iOS and the app.

**Comment by houser42** [comment]
Understood, Many thanks!
