### ISSUE TITLE
no state change in icons?

### ISSUE THREAD

**Issue by RezzZ** [basnijholt/lovelace-ios-themes#6]
just tried this ios theme and must say I like it. Only thing i noticed is that lights/switches (and other devices that have some form of on/off state) don't turn yellow when the are on, the icon I mean. only the switch ticker itself turns blue.

Would love it if the the also had some form on state changes.

eg, i've setup several entity cards with this attribute:
state_color: true
which looks like this with default theme:
![image](https://user-images.githubusercontent.com/70499/83884533-4d51a600-a745-11ea-975e-7b518dc39361.png)
![image](https://user-images.githubusercontent.com/70499/83884552-55a9e100-a745-11ea-9d64-534ecfa393be.png)

**Comment by basnijholt** [comment]
Hi @RezzZ,

If you change to the `-alternative` theme then you will get what you want ;)
