### ISSUE TITLE
QR code not shown when re-authenticating Tuya

### ISSUE THREAD

**Issue by EpicLPer** [basnijholt/lovelace-ios-themes#60]
Heya,

Home Assistant had it's 2024.02 update recently and changed some things around for Tuya, it now requires to re-authenticate via a QR code.  
When a custom theme is selected however the QR code doesn't show up, it seems to be an issue with the theme ([see here](https://github.com/home-assistant/core/issues/110186#issuecomment-1937398886)).

Thanks already for a fix :)

**Comment by osterman** [comment]
Can confirm this behavior as well.

**Comment by Nezz** [comment]
This is caused by these two variables:
```
--rgb-primary-text-color: 255,255,255
--rgb-card-background-color: 255,255,255
```

**Comment by Nezz** [comment]
After some googling it seems that some QR code readers struggle with white-on-black QR codes, so `--rgb-primary-text-color` should be set to black to be on the safe side.

**Comment by basnijholt** [comment]
@Nezz, I am very thankful that you are looking into these issues!
