### ISSUE TITLE
Slider tooltip background matches font color, making it unreadable

### ISSUE THREAD

**Issue by MasterDevwi** [basnijholt/lovelace-ios-themes#64]
Tooltips on sliders (like those for lights) are unreadable since both the background color and text color are white. I've confirmed this issue only repros when a lovelace-ios-themes theme is enabled. This has been broken for at least a few months, including on Home Assistant 2024.4.0.

<img width="158" alt="image" src="https://github.com/basnijholt/lovelace-ios-themes/assets/5544757/91205711-1b32-4db4-8940-e2ab3d8a6494">

@basnijholt would it be possible to please fix this so we can see what percentage we're setting lights and other entities to? I love this theme and would like to continue using it if possible.

**Comment by Nezz** [comment]
This issue stems from these two CSS entries:
```
--primary-text-color: #FFF;
--clear-background-color: #ffffff
```

**Comment by basnijholt** [comment]
Could you make a PR? 😃

**Comment by Nezz** [comment]
Already made one :)

**Comment by basnijholt** [comment]
Great! Just released https://github.com/basnijholt/lovelace-ios-themes/releases/tag/v2.12.0

**Comment by MasterDevwi** [comment]
Thank you so much! It seems to be working great.

**Comment by MasterDevwi** [comment]
Along the same lines, the only other similar issue I've encountered is with the favorites view in custom:sonos-card. It looks perfect in most themes, but not in lovelace-ios-themes. 

![image](https://github.com/basnijholt/lovelace-ios-themes/assets/5544757/19038dba-00af-47e5-9f81-56174389c598)

It seems to be using the title stylesheet, but both are light gray so they conflict and present readability issues.

![image](https://github.com/basnijholt/lovelace-ios-themes/assets/5544757/d49caec5-2d5a-4768-a035-0815050ff2ee)

**Comment by basnijholt** [comment]
@MasterDevwi, would you be able to make a PR? 😄

**Comment by Nezz** [comment]
@MasterDevwi that issue and #60 both stem from `--rgb-card-background-color`, so I'll open a PR that makes it dark.

**Comment by MasterDevwi** [comment]
> @MasterDevwi, would you be able to make a PR? 😄

I spent some time investigating if I could do it myself before filing this original bug, but I hit a few roadblocks. Thank you so much to you and @Nezz for fixing it!
