### ISSUE TITLE
Q: option to change transparancy?

### ISSUE THREAD

**Issue by RezzZ** [basnijholt/lovelace-ios-themes#7]
Is there a way to change the transparency of the elements? It's a bit too transparent imho.
example where transparency is tad hindering:
![image](https://user-images.githubusercontent.com/70499/84007279-6db17880-a970-11ea-8596-cf6287201ce5.png)

**Comment by MMMM78** [comment]
I feel the same. The transparency can be a bit less or allmost 0%. Is there a way to change it? Now it's difficult to read pages.


![image](https://user-images.githubusercontent.com/36551447/94189126-a25b2880-feaa-11ea-994c-e04de58013cf.png)

**Comment by basnijholt** [comment]
I agree it's not optimal. I will change it to a lower transparency!

**Comment by basnijholt** [comment]
I have fixed it in v2.3.0.

**Comment by MMMM78** [comment]
Looks nice now! Thanks for the fix!
