### ISSUE TITLE
Stopped working after new HACS update 22/8-24

### ISSUE THREAD

**Issue by ekalle-swe** [basnijholt/lovelace-ios-themes#73]
All iOS themes are just ignored and will result in black&white screen.
Tested to clear cache and to reload iOS theme but that doesn't help.
There was something in breaking news in the latest HACS update but I can't find it again.
I'm terrible at navigating GitHub. It's just like a bowl of spaghetti to me 😂

**Comment by andy149** [comment]
+1 
however I'm getting different results depending on what device I'm using. 
Google home display using Dashcast shows default white 
Windows 11 Mozilla browser shows the correct ios theme
iPhone shows the correct theme. 

All when loading the same dashboard.

**Comment by ekalle-swe** [comment]
I noticed it worked for a bit, until you clear the cache. Still have one iPad that is working but just a question of time

**Comment by ekalle-swe** [comment]
> PR #70 will resolve this issue, once an update to the theme is released that includes it. It was recently accepted and merged.

How far into the future is this?
Have hundred of references to the theme in my dash and would not like to go through all that. Is there a beta channel active with this update merged or can you please do a beta to ease our sufferings?

**Comment by rohankapoorcom** [comment]
It was merged ~10 hours ago. @basnijholt do you mind creating a release that includes it?

Alternatively @ekalle-swe - you can replace the theme file on your local install with the contents of https://raw.githubusercontent.com/basnijholt/lovelace-ios-themes/master/themes/ios-themes.yaml to fix your own installation.

**Comment by basnijholt** [comment]
Done! Just released v2.14.0.

**Comment by ekalle-swe** [comment]
Perfect!


> PR #70 will resolve this issue, once an update to the theme is released that includes it. It was recently accepted and merged.

10 hours ago? 😂 Accepted and merged in my world means it's been processed on at least 2 project meetings and then given to s project leader that has to book staff resources..... That's why my hopes was to an early beta.
Fixed within minutes was not even a possibility, in my mind. Tnx!

**Comment by ekalle-swe** [comment]
It just woooorked!
