### ISSUE TITLE
Badges are not following theme

### ISSUE THREAD

**Issue by okruts** [basnijholt/lovelace-ios-themes#75]
![image](https://github.com/user-attachments/assets/d232cf2f-528b-47cb-a07e-27ee25470c1c)

New badges feature not following theme. I'm not 100% sure on which side it can be fixed. In badges itself there is no option to select background color or possibility to use `card_mod`

**Comment by basnijholt** [comment]
Seems to be fixed in the new version of Home Assistant! :tada:

<img width="963" alt="image" src="https://github.com/user-attachments/assets/da4836d5-f930-496a-85dd-76769bd3ca45">
