### ISSUE TITLE
Dark mode not sticking

### ISSUE THREAD

**Issue by bobbynobble** [basnijholt/lovelace-ios-themes#8]
Using your automation to switch dark mode on but regularly find it has reset itself, them works perfectly otherwise thank you. Can't find any consistent circumstances for when it happens and it's the same on all devices. 

Any ideas or have I just missed something obvious?

**Comment by basnijholt** [comment]
I have observed this too. Next time I notice it, I'll investigate. I suspect there is a bug with HA and it not properly resetting the correct state.

**Comment by b1g1an** [comment]
Anymore thoughts on this? It's suddenly started doing it a lot more on my set up.

**Comment by basnijholt** [comment]
Have you tried something like this: https://github.com/basnijholt/home-assistant-config/blob/43046bc7a2cb1b0d211bddb50d24605c3622335d/automations/frontend.yaml#L33-L50

Where you reset the theme on `homeassistant.start`?

**Comment by b1g1an** [comment]
Thanks, I'll give it a go though not sure it's only a restart that resets it.

**Comment by b1g1an** [comment]
Well I'm an idiot, found I already had that automation installed and more damningly had your timed ones there too. Obviously just copied them without actually looking at what they did and all that's been happening was the daytime light mode one kept triggering.

Please close this and bury it under a rock somewhere where no one will ever see what's a dummy I am again.

**Comment by basnijholt** [comment]
OK great, happy to hear that you solved it!
